"""Generate and validate the Module 1 data dictionary for PaySim."""
from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from config import DATA_PROCESSED, DOCS
from synth_context import FIELD_META, GEN

DICT_PATH = DOCS / "data_dictionary.md"

BASE_ROWS = [
    ("step", "int", "hours", "1..743", "Simulation time; one step is one hour."),
    ("type", "category", "-", "PAYMENT/TRANSFER/CASH_OUT/CASH_IN/DEBIT", "Transaction type; real fraud occurs only in TRANSFER and CASH_OUT."),
    ("amount", "float", "currency", ">=0", "Transaction amount and proxy for fraud loss."),
    ("nameOrig", "string", "-", "C########", "Origin customer id from PaySim; almost always single-use in the real file."),
    ("oldbalanceOrg", "float", "currency", ">=0", "Origin balance before transaction."),
    ("newbalanceOrig", "float", "currency", ">=0", "Origin balance after transaction."),
    ("nameDest", "string", "-", "C... or M...", "Destination account; repeated customer destinations are useful mule candidates for later feature engineering."),
    ("oldbalanceDest", "float", "currency", ">=0", "Destination balance before transaction."),
    ("newbalanceDest", "float", "currency", ">=0", "Destination balance after transaction."),
    ("isFraud", "int", "flag", "{0,1}", "Target label."),
    ("isFlaggedFraud", "int", "flag", "{0,1}", "PaySim's built-in rule flag for very large transfers."),
]


def synthetic_table() -> str:
    rows = []
    for col, meta in FIELD_META.items():
        rows.append({
            "Column": col,
            "Layer": meta["layer"],
            "Type": meta["type"],
            "Unit": meta["unit"],
            "Valid range": meta["range"],
            "Fraud-cond.?": meta["fraud_conditioned"],
            "Generation logic / business assumption": meta["logic"],
        })
    return pd.DataFrame(rows).to_markdown(index=False)


def build_dictionary() -> str:
    base = pd.DataFrame(BASE_ROWS, columns=["Column", "Type", "Unit", "Valid range", "Description"])
    return "\n".join([
        "# Data Dictionary — PaySim E-Commerce Fraud Detection\n",
        "## 0. Overview\n",
        "- Source: Kaggle `rupakroy/online-payments-fraud-detection-dataset`.\n",
        "- Active raw file: `data/online-payments-fraud-detection-dataset/PS_20174392719_1491204439457_log.csv`.\n",
        "- Full rows: 6,362,620. Fraud rows: 8,213. Fraud prevalence: approximately 0.129%.\n",
        "- Module 1 default artifact is a stratified 15% sample that preserves the natural fraud rate.\n",
        "- Synthetic context is generated by `src/synth_context.py` with `SEED=42`.\n",
        "## 1. Base PaySim Columns\n",
        base.to_markdown(index=False) + "\n",
        "## 2. Synthetic Context Columns\n",
        synthetic_table() + "\n",
        "## 3. Generation Parameters\n",
        f"- `n_customers`: {GEN['n_customers']}\n",
        f"- `reveal_rate`: {GEN['reveal_rate']}\n",
        f"- `legit_noise`: {GEN['legit_noise']}\n",
        f"- `account_age_days`: legit={GEN['account_age_days']['legit']}, fraud={GEN['account_age_days']['fraud']}\n",
        f"- `high_risk_country`: legit={GEN['high_risk_country']['legit']}, fraud={GEN['high_risk_country']['fraud']}\n",
        f"- `is_disposable_email`: legit={GEN['is_disposable_email']['legit']}, fraud={GEN['is_disposable_email']['fraud']}\n",
        f"- `is_new_device`: legit={GEN['is_new_device']['legit']}, fraud={GEN['is_new_device']['fraud']}\n",
        f"- `shipping_billing_mismatch`: legit={GEN['shipping_billing_mismatch']['legit']}, fraud={GEN['shipping_billing_mismatch']['fraud']}\n",
        f"- `num_failed_payment_attempts`: legit={GEN['num_failed_payment_attempts']['legit']}, fraud={GEN['num_failed_payment_attempts']['fraud']}\n",
        f"- `ip_offset_deg`: legit={GEN['ip_offset_deg']['legit']}, fraud={GEN['ip_offset_deg']['fraud']}\n",
        "## 4. Design Notes & Limitations\n",
        "- Faker identity columns (`customer_name`, `email`, `billing_city`) are analyst-facing context and should not be treated as real customer PII.\n",
        "- Real `nameOrig` is almost always single-use, so synthetic customer velocity is illustrative. Later feature engineering should prefer real repeated `nameDest` aggregation for mule-account signals.\n",
        "- PaySim balance fields are highly predictive; a realistic modelling scenario should compare models with and without post-transaction balance-reconciliation features.\n",
        "- Synthetic risk fields are intentionally overlapping by using `reveal_rate` and `legit_noise`; they should support realism, not create perfect target leakage.\n",
    ])


def check_dictionary(path: Path = DICT_PATH) -> None:
    if not path.exists():
        raise FileNotFoundError(f"{path} does not exist. Run without --check first.")
    text = path.read_text(encoding="utf-8")
    missing_doc = [col for col in FIELD_META if col not in text]
    if missing_doc:
        raise AssertionError(f"Dictionary missing synthetic columns: {missing_doc}")
    data_path = DATA_PROCESSED / "transactions_context.parquet"
    if data_path.exists():
        cols = set(pd.read_parquet(data_path).columns)
        missing_data = [col for col in FIELD_META if col not in cols]
        if missing_data:
            raise AssertionError(f"Processed parquet missing synthetic columns: {missing_data}")
    print("[dict] check passed")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.check:
        check_dictionary()
    else:
        DICT_PATH.write_text(build_dictionary(), encoding="utf-8")
        print(f"[dict] wrote {DICT_PATH}")


if __name__ == "__main__":
    main()
